version: '3.8'

services:
  openapi-generator:
    build:
      context: .
      dockerfile: Dockerfile.openapi-generator
    volumes:
      - ./src:/app/src
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no" 