import { ChangeDetectionStrategy, Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { CustomButtonComponent } from '../../shared/components/custom-button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { Store } from '@ngrx/store';
import {
    cancelCreateCategoryButtonClickedAction,
    createCategoryFormSubmittedAction,
} from '../../../application/categories';

@Component({
    selector: 'app-category-create-form',
    standalone: true,
    imports: [
        CommonModule,
        ReactiveFormsModule,
        CustomButtonComponent,
        MatFormFieldModule,
        MatInputModule,
    ],
    templateUrl: './category-create-form.component.html',
    styleUrl: './category-create-form.component.less',
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CategoryCreateFormComponent {
    protected categoryForm: FormGroup = this.fb.group({
        name: ['', [Validators.required]],
        emoji: ['🍎', [Validators.required]],
    });

    protected emojis: string[] = [
        '🍎',
        '🍏',
        '🍐',
        '🍊',
        '🍋',
        '🍌',
        '🍉',
        '🍇',
        '🍓',
        '🍈',
        '🍒',
        '🍑',
        '🥭',
        '🍍',
        '🥥',
        '🥝',
        '🍅',
        '🥑',
        '🍆',
        '🥔',
        '🥕',
        '🌽',
        '🌶️',
        '🥒',
        '🥬',
        '🥦',
        '🧄',
        '🧅',
        '🍄',
        '🥜',
        '🌰',
        '🍞',
        '🥐',
        '🥖',
        '🥨',
        '🥯',
        '🥞',
        '🧇',
        '🧀',
        '🍖',
        '🍗',
        '🥩',
        '🥓',
        '🍔',
        '🍟',
        '🍕',
        '🌭',
        '🥪',
        '🌮',
        '🌯',
        '🥙',
        '🧆',
        '🥚',
        '🍳',
        '🥘',
        '🍲',
        '🥣',
        '🥗',
        '🍿',
        '🧈',
        '🧂',
        '🥫',
        '🍱',
        '🍘',
        '🍙',
        '🍚',
        '🍛',
        '🍜',
        '🍝',
        '🍠',
        '🍢',
        '🍣',
        '🍤',
        '🍥',
        '🥮',
        '🍡',
        '🥟',
        '🥠',
        '🥡',
        '🍦',
        '🍧',
        '🍨',
        '🍩',
        '🍪',
        '🎂',
        '🍰',
        '🧁',
        '🥧',
        '🍫',
        '🍬',
        '🍭',
        '🍮',
        '🍯',
        '🍼',
        '🥛',
        '☕',
        '🍵',
        '🍶',
        '🍾',
        '🍷',
        '🍸',
        '🍹',
        '🍺',
        '🍻',
        '🥂',
        '🥃',
        '🥤',
        '🧃',
        '🧉',
        '🧊',
        '🥢',
        '🍽️',
        '🍴',
        '🥄',
        '🔪',
        '🏺',
        '🧹',
        '🧯',
        '🛒',
        '🚪',
        '🛋️',
        '🪑',
        '🚿',
        '🛁',
        '🧴',
        '🧷',
        '🧺',
        '🧻',
        '🧼',
        '🧽',
        '📱',
        '💻',
        '🖥️',
        '🖨️',
        '⌨️',
        '🖱️',
        '💾',
        '💿',
        '📀',
        '🧮',
        '🎮',
        '🕹️',
        '🎲',
        '🎭',
        '🎨',
        '🧩',
        '🎺',
        '🎸',
        '🎻',
        '🎬',
        '📚',
        '📖',
        '📰',
        '🏆',
        '⚽',
        '🏀',
        '🏈',
        '⚾',
        '🥎',
        '🎾',
        '🏐',
        '🏉',
        '🎱',
        '🏓',
        '🏸',
        '🥅',
        '⛳',
        '🎣',
        '🤿',
        '🎽',
        '🛹',
        '🛷',
        '⛸️',
        '🥌',
        '🎿',
    ];

    constructor(
        private fb: FormBuilder,
        private store: Store
    ) {}

    protected submitForm(): void {
        if (this.categoryForm.valid) {
            this.store.dispatch(createCategoryFormSubmittedAction(this.categoryForm.value));
        }
    }

    protected cancelForm(): void {
        this.store.dispatch(cancelCreateCategoryButtonClickedAction());
    }
}
